#!/bin/sh
#
# Creates a temporary clone and runs ./build.sh.
# Part of Kamila's Git hooks (https://github.com/anotherkamila/git-hooks).

set -e  # fail on error
#set -x  # be talkative

GIT_REPO="$(readlink -f "$GIT_DIR")"
REPO_NAME="$(basename "$GIT_REPO")"
[ -f "$GIT_REPO/hooks/settings.sh" ] && . "$GIT_REPO/hooks/settings.sh"
CLONE_TO="${CLONE_TO:-/tmp/builddir-$REPO_NAME}"

PUSHED_BRANCH="$(cut -f3 | cut -d/ -f3)"  # post-receive gets stuff on stdin

[ -d "$CLONE_TO" ] || git clone "$GIT_REPO" "$CLONE_TO" >&2
cd "$CLONE_TO"
export GIT_DIR='.git'  # from now on, we want to work with the cloned repo's .git

git fetch --all
git checkout -f "$PUSHED_BRANCH"
git pull --recurse-submodules

. "$GIT_REPO/hooks/build.sh"

exit 0
