#!/bin/sh
#
# Builds and deploys with _bin/{setup,deploy}.

#set -x  # be talkative

LIB="$(dirname "$(readlink -f "$0")")/lib.sh"
DOCUMENT_ROOT="$(cat "$(readlink -f "$GIT_DIR")/hooks/DOCUMENT_ROOT")"

. "$LIB"

cd "$(clone_to_tmp)"
export GIT_DIR='.git'
npm update
npm run build
cp -r public/ "$DOCUMENT_ROOT"

exit 0
